export const FETCH_ALL = "FETCH_ALL";
export const COMPLETE_TODO = "COMPLETE_TODO";
export const SET_ADD_TODO_TEXT = "SET_ADD_TODO_TEXT";
export const TOGGLE_COMPLETE_ALL = "TOGGLE_COMPLETE_ALL";
export const TOGGLE_COMPLETE = "TOGGLE_COMPLETE";
export const HIDE_COMPLETE = "HIDE_COMPLETE";
export const FILTER_TODOS = "FILTER_TODOS";